#spring:
#  cloud:
#    gateway:
#      routes:
#      - id: users-fetch
#        uri: lb://USER-SERVICE
#        predicates:
#        - Path=/user
#
##    gateway:
##      discovery:
##        locator:
##          enabled: true
##          lower-case-service-id: true
