#spring:
#  cloud:
#    gateway:
#      routes:
#        - id: users-fetch
#          uri: lb://USER-SERVICE
#          predicates:
#            - Path=/user
#            - Method=GET
#          filters:
#            - RemoveRequestHeader=Cookie
#
##    gateway:
##      discovery:
##        locator:
##          enabled: true
##          lower-case-service-id: true
